// Code generated by MockGen. DO NOT EDIT.
// Source: suiclient/client.go
//
// Generated by this command:
//
//	mockgen -source=suiclient/client.go -destination=genmock/suiclient/client.go
//

// Package mock_suiclient is a generated GoMock package.
package mock_suiclient

import (
	context "context"
	reflect "reflect"

	lib "github.com/utila-io/go-sui-sdk/lib"
	sui_types "github.com/utila-io/go-sui-sdk/sui_types"
	suiclient "github.com/utila-io/go-sui-sdk/suiclient"
	types "github.com/utila-io/go-sui-sdk/types"
	gomock "go.uber.org/mock/gomock"
)

// MockSuiClient is a mock of SuiClient interface.
type MockSuiClient struct {
	ctrl     *gomock.Controller
	recorder *MockSuiClientMockRecorder
	isgomock struct{}
}

// MockSuiClientMockRecorder is the mock recorder for MockSuiClient.
type MockSuiClientMockRecorder struct {
	mock *MockSuiClient
}

// NewMockSuiClient creates a new mock instance.
func NewMockSuiClient(ctrl *gomock.Controller) *MockSuiClient {
	mock := &MockSuiClient{ctrl: ctrl}
	mock.recorder = &MockSuiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuiClient) EXPECT() *MockSuiClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSuiClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSuiClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSuiClient)(nil).Close))
}

// DevInspectTransactionBlock mocks base method.
func (m *MockSuiClient) DevInspectTransactionBlock(ctx context.Context, sender sui_types.SuiAddress, txKindBytes lib.Base64Data, gasPrice *types.SafeSuiBigInt[uint64], epoch *uint64) (*types.DevInspectResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DevInspectTransactionBlock", ctx, sender, txKindBytes, gasPrice, epoch)
	ret0, _ := ret[0].(*types.DevInspectResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DevInspectTransactionBlock indicates an expected call of DevInspectTransactionBlock.
func (mr *MockSuiClientMockRecorder) DevInspectTransactionBlock(ctx, sender, txKindBytes, gasPrice, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DevInspectTransactionBlock", reflect.TypeOf((*MockSuiClient)(nil).DevInspectTransactionBlock), ctx, sender, txKindBytes, gasPrice, epoch)
}

// DryRunTransaction mocks base method.
func (m *MockSuiClient) DryRunTransaction(ctx context.Context, txBytes lib.Base64Data) (*types.DryRunTransactionBlockResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DryRunTransaction", ctx, txBytes)
	ret0, _ := ret[0].(*types.DryRunTransactionBlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DryRunTransaction indicates an expected call of DryRunTransaction.
func (mr *MockSuiClientMockRecorder) DryRunTransaction(ctx, txBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DryRunTransaction", reflect.TypeOf((*MockSuiClient)(nil).DryRunTransaction), ctx, txBytes)
}

// ExecuteTransactionBlock mocks base method.
func (m *MockSuiClient) ExecuteTransactionBlock(ctx context.Context, txBytes lib.Base64Data, signatures []any, options *types.SuiTransactionBlockResponseOptions, requestType types.ExecuteTransactionRequestType) (*types.SuiTransactionBlockResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTransactionBlock", ctx, txBytes, signatures, options, requestType)
	ret0, _ := ret[0].(*types.SuiTransactionBlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteTransactionBlock indicates an expected call of ExecuteTransactionBlock.
func (mr *MockSuiClientMockRecorder) ExecuteTransactionBlock(ctx, txBytes, signatures, options, requestType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTransactionBlock", reflect.TypeOf((*MockSuiClient)(nil).ExecuteTransactionBlock), ctx, txBytes, signatures, options, requestType)
}

// GetAllBalances mocks base method.
func (m *MockSuiClient) GetAllBalances(ctx context.Context, owner sui_types.SuiAddress) ([]types.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBalances", ctx, owner)
	ret0, _ := ret[0].([]types.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBalances indicates an expected call of GetAllBalances.
func (mr *MockSuiClientMockRecorder) GetAllBalances(ctx, owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBalances", reflect.TypeOf((*MockSuiClient)(nil).GetAllBalances), ctx, owner)
}

// GetBalance mocks base method.
func (m *MockSuiClient) GetBalance(ctx context.Context, owner sui_types.SuiAddress, coinType string) (*types.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, owner, coinType)
	ret0, _ := ret[0].(*types.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockSuiClientMockRecorder) GetBalance(ctx, owner, coinType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockSuiClient)(nil).GetBalance), ctx, owner, coinType)
}

// GetCheckpoint mocks base method.
func (m *MockSuiClient) GetCheckpoint(ctx context.Context, seqNum uint64) (*types.Checkpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCheckpoint", ctx, seqNum)
	ret0, _ := ret[0].(*types.Checkpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCheckpoint indicates an expected call of GetCheckpoint.
func (mr *MockSuiClientMockRecorder) GetCheckpoint(ctx, seqNum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckpoint", reflect.TypeOf((*MockSuiClient)(nil).GetCheckpoint), ctx, seqNum)
}

// GetCheckpointTransactions mocks base method.
func (m *MockSuiClient) GetCheckpointTransactions(ctx context.Context, seqNum uint64, options types.SuiTransactionBlockResponseOptions) ([]*types.SuiTransactionBlockResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCheckpointTransactions", ctx, seqNum, options)
	ret0, _ := ret[0].([]*types.SuiTransactionBlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCheckpointTransactions indicates an expected call of GetCheckpointTransactions.
func (mr *MockSuiClientMockRecorder) GetCheckpointTransactions(ctx, seqNum, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckpointTransactions", reflect.TypeOf((*MockSuiClient)(nil).GetCheckpointTransactions), ctx, seqNum, options)
}

// GetCheckpoints mocks base method.
func (m *MockSuiClient) GetCheckpoints(ctx context.Context, startSeqNum uint64, limit int, opts ...types.CheckpointOption) ([]*types.Checkpoint, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, startSeqNum, limit}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCheckpoints", varargs...)
	ret0, _ := ret[0].([]*types.Checkpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCheckpoints indicates an expected call of GetCheckpoints.
func (mr *MockSuiClientMockRecorder) GetCheckpoints(ctx, startSeqNum, limit any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, startSeqNum, limit}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckpoints", reflect.TypeOf((*MockSuiClient)(nil).GetCheckpoints), varargs...)
}

// GetCoinMetadata mocks base method.
func (m *MockSuiClient) GetCoinMetadata(ctx context.Context, coinType string) (*types.SuiCoinMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoinMetadata", ctx, coinType)
	ret0, _ := ret[0].(*types.SuiCoinMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoinMetadata indicates an expected call of GetCoinMetadata.
func (mr *MockSuiClientMockRecorder) GetCoinMetadata(ctx, coinType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoinMetadata", reflect.TypeOf((*MockSuiClient)(nil).GetCoinMetadata), ctx, coinType)
}

// GetCoins mocks base method.
func (m *MockSuiClient) GetCoins(ctx context.Context, owner sui_types.SuiAddress, coinType, cursor *string, limit uint) (*suiclient.CoinPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoins", ctx, owner, coinType, cursor, limit)
	ret0, _ := ret[0].(*suiclient.CoinPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoins indicates an expected call of GetCoins.
func (mr *MockSuiClientMockRecorder) GetCoins(ctx, owner, coinType, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoins", reflect.TypeOf((*MockSuiClient)(nil).GetCoins), ctx, owner, coinType, cursor, limit)
}

// GetLatestCheckpointSequenceNumber mocks base method.
func (m *MockSuiClient) GetLatestCheckpointSequenceNumber(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestCheckpointSequenceNumber", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestCheckpointSequenceNumber indicates an expected call of GetLatestCheckpointSequenceNumber.
func (mr *MockSuiClientMockRecorder) GetLatestCheckpointSequenceNumber(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestCheckpointSequenceNumber", reflect.TypeOf((*MockSuiClient)(nil).GetLatestCheckpointSequenceNumber), ctx)
}

// GetObject mocks base method.
func (m *MockSuiClient) GetObject(ctx context.Context, objID sui_types.ObjectID, options *types.SuiObjectDataOptions) (*types.SuiObjectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, objID, options)
	ret0, _ := ret[0].(*types.SuiObjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockSuiClientMockRecorder) GetObject(ctx, objID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockSuiClient)(nil).GetObject), ctx, objID, options)
}

// GetReferenceGasPrice mocks base method.
func (m *MockSuiClient) GetReferenceGasPrice(ctx context.Context) (*types.SafeSuiBigInt[uint64], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferenceGasPrice", ctx)
	ret0, _ := ret[0].(*types.SafeSuiBigInt[uint64])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReferenceGasPrice indicates an expected call of GetReferenceGasPrice.
func (mr *MockSuiClientMockRecorder) GetReferenceGasPrice(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferenceGasPrice", reflect.TypeOf((*MockSuiClient)(nil).GetReferenceGasPrice), ctx)
}

// GetTransactionBlock mocks base method.
func (m *MockSuiClient) GetTransactionBlock(ctx context.Context, digest sui_types.TransactionDigest, options types.SuiTransactionBlockResponseOptions) (*types.SuiTransactionBlockResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionBlock", ctx, digest, options)
	ret0, _ := ret[0].(*types.SuiTransactionBlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionBlock indicates an expected call of GetTransactionBlock.
func (mr *MockSuiClientMockRecorder) GetTransactionBlock(ctx, digest, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionBlock", reflect.TypeOf((*MockSuiClient)(nil).GetTransactionBlock), ctx, digest, options)
}

// MultiGetObjects mocks base method.
func (m *MockSuiClient) MultiGetObjects(ctx context.Context, objIDs []sui_types.ObjectID, options *types.SuiObjectDataOptions) ([]types.SuiObjectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MultiGetObjects", ctx, objIDs, options)
	ret0, _ := ret[0].([]types.SuiObjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MultiGetObjects indicates an expected call of MultiGetObjects.
func (mr *MockSuiClientMockRecorder) MultiGetObjects(ctx, objIDs, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MultiGetObjects", reflect.TypeOf((*MockSuiClient)(nil).MultiGetObjects), ctx, objIDs, options)
}

// MultiGetTransactionBlocks mocks base method.
func (m *MockSuiClient) MultiGetTransactionBlocks(ctx context.Context, digests []sui_types.TransactionDigest, options types.SuiTransactionBlockResponseOptions) ([]*types.SuiTransactionBlockResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MultiGetTransactionBlocks", ctx, digests, options)
	ret0, _ := ret[0].([]*types.SuiTransactionBlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MultiGetTransactionBlocks indicates an expected call of MultiGetTransactionBlocks.
func (mr *MockSuiClientMockRecorder) MultiGetTransactionBlocks(ctx, digests, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MultiGetTransactionBlocks", reflect.TypeOf((*MockSuiClient)(nil).MultiGetTransactionBlocks), ctx, digests, options)
}
