// Package rpcv2 holds the generated sui.rpc.v2 protobuf and gRPC bindings,
// plus the hand-written conversions from those wire messages to the SDK's
// internal types (the types, sui_types and lib packages).
//
// File conventions:
//
//   - *.pb.go, *_grpc.pb.go       generated by `make proto` (buf). Do not edit.
//   - <proto>_convert.go          hand-written; the conversions for messages
//     declared in the like-named <proto>.pb.go, plus the free functions that
//     belong with them.
//   - <proto>_<topic>_convert.go  a second convert file for the same anchor,
//     where one file would grow unwieldy. Only
//     effects_objectchange_convert.go today; there is no
//     effects_objectchange.proto.
//   - convert_*.go                hand-written; conversion code with no
//     protobuf message to hang it off. The convert_ prefix cannot collide with
//     a generated name, since buf only ever writes <proto>.pb.go.
//
// The hand-written files are neither regenerated nor disposable: buf only ever
// writes *.pb.go, so they survive `make proto`. Do not run
// `buf generate --clean` and do not delete this directory wholesale. Tooling
// that skips generated code must key on the .pb.go suffix, not on this path.
//
// buf writes generated files but never removes them. If upstream renames or
// drops a .proto, `make proto` writes the new .pb.go and leaves the old one
// behind, which then redeclares its types and breaks the build. Delete the
// orphaned .pb.go by hand; `--clean` would take the hand-written files with it.
//
// A package-level coverage number is meaningless here, since the conversions
// share a package with ~21k lines of generated bindings (`go test -cover`
// reports ~19%). Filter the profile to the hand-written files instead:
//
//	go test -coverprofile=c.out ./clientv2/internal/pb/... &&
//	  go tool cover -func=c.out | grep -E '_convert\.go:|convert_[a-z_]*\.go:'
//
// The conversion entry point is a method named ToInternalType on the wire
// message, or ToInternalXxx where one message converts to more than one
// internal shape (see owner_convert.go).
package rpcv2
