// Code generated by MockGen. DO NOT EDIT.
// Source: clientv2/internal/pb/sui/rpc/v2/ledger_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=clientv2/internal/pb/sui/rpc/v2/ledger_service_grpc.pb.go -destination=clientv2/internal/genmock/pb/sui/rpc/v2/ledger_service_grpc.pb.go
//

// Package mock_rpcv2 is a generated GoMock package.
package mock_rpcv2

import (
	context "context"
	reflect "reflect"

	rpcv2 "github.com/utila-io/go-sui-sdk/clientv2/internal/pb/sui/rpc/v2"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockLedgerServiceClient is a mock of LedgerServiceClient interface.
type MockLedgerServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerServiceClientMockRecorder
	isgomock struct{}
}

// MockLedgerServiceClientMockRecorder is the mock recorder for MockLedgerServiceClient.
type MockLedgerServiceClientMockRecorder struct {
	mock *MockLedgerServiceClient
}

// NewMockLedgerServiceClient creates a new mock instance.
func NewMockLedgerServiceClient(ctrl *gomock.Controller) *MockLedgerServiceClient {
	mock := &MockLedgerServiceClient{ctrl: ctrl}
	mock.recorder = &MockLedgerServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerServiceClient) EXPECT() *MockLedgerServiceClientMockRecorder {
	return m.recorder
}

// BatchGetObjects mocks base method.
func (m *MockLedgerServiceClient) BatchGetObjects(ctx context.Context, in *rpcv2.BatchGetObjectsRequest, opts ...grpc.CallOption) (*rpcv2.BatchGetObjectsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchGetObjects", varargs...)
	ret0, _ := ret[0].(*rpcv2.BatchGetObjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetObjects indicates an expected call of BatchGetObjects.
func (mr *MockLedgerServiceClientMockRecorder) BatchGetObjects(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetObjects", reflect.TypeOf((*MockLedgerServiceClient)(nil).BatchGetObjects), varargs...)
}

// BatchGetTransactions mocks base method.
func (m *MockLedgerServiceClient) BatchGetTransactions(ctx context.Context, in *rpcv2.BatchGetTransactionsRequest, opts ...grpc.CallOption) (*rpcv2.BatchGetTransactionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchGetTransactions", varargs...)
	ret0, _ := ret[0].(*rpcv2.BatchGetTransactionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetTransactions indicates an expected call of BatchGetTransactions.
func (mr *MockLedgerServiceClientMockRecorder) BatchGetTransactions(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetTransactions", reflect.TypeOf((*MockLedgerServiceClient)(nil).BatchGetTransactions), varargs...)
}

// GetCheckpoint mocks base method.
func (m *MockLedgerServiceClient) GetCheckpoint(ctx context.Context, in *rpcv2.GetCheckpointRequest, opts ...grpc.CallOption) (*rpcv2.GetCheckpointResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCheckpoint", varargs...)
	ret0, _ := ret[0].(*rpcv2.GetCheckpointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCheckpoint indicates an expected call of GetCheckpoint.
func (mr *MockLedgerServiceClientMockRecorder) GetCheckpoint(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckpoint", reflect.TypeOf((*MockLedgerServiceClient)(nil).GetCheckpoint), varargs...)
}

// GetEpoch mocks base method.
func (m *MockLedgerServiceClient) GetEpoch(ctx context.Context, in *rpcv2.GetEpochRequest, opts ...grpc.CallOption) (*rpcv2.GetEpochResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetEpoch", varargs...)
	ret0, _ := ret[0].(*rpcv2.GetEpochResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpoch indicates an expected call of GetEpoch.
func (mr *MockLedgerServiceClientMockRecorder) GetEpoch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpoch", reflect.TypeOf((*MockLedgerServiceClient)(nil).GetEpoch), varargs...)
}

// GetObject mocks base method.
func (m *MockLedgerServiceClient) GetObject(ctx context.Context, in *rpcv2.GetObjectRequest, opts ...grpc.CallOption) (*rpcv2.GetObjectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObject", varargs...)
	ret0, _ := ret[0].(*rpcv2.GetObjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockLedgerServiceClientMockRecorder) GetObject(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockLedgerServiceClient)(nil).GetObject), varargs...)
}

// GetServiceInfo mocks base method.
func (m *MockLedgerServiceClient) GetServiceInfo(ctx context.Context, in *rpcv2.GetServiceInfoRequest, opts ...grpc.CallOption) (*rpcv2.GetServiceInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetServiceInfo", varargs...)
	ret0, _ := ret[0].(*rpcv2.GetServiceInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceInfo indicates an expected call of GetServiceInfo.
func (mr *MockLedgerServiceClientMockRecorder) GetServiceInfo(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceInfo", reflect.TypeOf((*MockLedgerServiceClient)(nil).GetServiceInfo), varargs...)
}

// GetTransaction mocks base method.
func (m *MockLedgerServiceClient) GetTransaction(ctx context.Context, in *rpcv2.GetTransactionRequest, opts ...grpc.CallOption) (*rpcv2.GetTransactionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTransaction", varargs...)
	ret0, _ := ret[0].(*rpcv2.GetTransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockLedgerServiceClientMockRecorder) GetTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockLedgerServiceClient)(nil).GetTransaction), varargs...)
}

// ListCheckpoints mocks base method.
func (m *MockLedgerServiceClient) ListCheckpoints(ctx context.Context, in *rpcv2.ListCheckpointsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rpcv2.ListCheckpointsResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListCheckpoints", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[rpcv2.ListCheckpointsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCheckpoints indicates an expected call of ListCheckpoints.
func (mr *MockLedgerServiceClientMockRecorder) ListCheckpoints(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCheckpoints", reflect.TypeOf((*MockLedgerServiceClient)(nil).ListCheckpoints), varargs...)
}

// ListEvents mocks base method.
func (m *MockLedgerServiceClient) ListEvents(ctx context.Context, in *rpcv2.ListEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rpcv2.ListEventsResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListEvents", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[rpcv2.ListEventsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockLedgerServiceClientMockRecorder) ListEvents(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockLedgerServiceClient)(nil).ListEvents), varargs...)
}

// ListTransactions mocks base method.
func (m *MockLedgerServiceClient) ListTransactions(ctx context.Context, in *rpcv2.ListTransactionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rpcv2.ListTransactionsResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTransactions", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[rpcv2.ListTransactionsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockLedgerServiceClientMockRecorder) ListTransactions(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockLedgerServiceClient)(nil).ListTransactions), varargs...)
}

// MockLedgerServiceServer is a mock of LedgerServiceServer interface.
type MockLedgerServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerServiceServerMockRecorder
	isgomock struct{}
}

// MockLedgerServiceServerMockRecorder is the mock recorder for MockLedgerServiceServer.
type MockLedgerServiceServerMockRecorder struct {
	mock *MockLedgerServiceServer
}

// NewMockLedgerServiceServer creates a new mock instance.
func NewMockLedgerServiceServer(ctrl *gomock.Controller) *MockLedgerServiceServer {
	mock := &MockLedgerServiceServer{ctrl: ctrl}
	mock.recorder = &MockLedgerServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerServiceServer) EXPECT() *MockLedgerServiceServerMockRecorder {
	return m.recorder
}

// BatchGetObjects mocks base method.
func (m *MockLedgerServiceServer) BatchGetObjects(arg0 context.Context, arg1 *rpcv2.BatchGetObjectsRequest) (*rpcv2.BatchGetObjectsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetObjects", arg0, arg1)
	ret0, _ := ret[0].(*rpcv2.BatchGetObjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetObjects indicates an expected call of BatchGetObjects.
func (mr *MockLedgerServiceServerMockRecorder) BatchGetObjects(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetObjects", reflect.TypeOf((*MockLedgerServiceServer)(nil).BatchGetObjects), arg0, arg1)
}

// BatchGetTransactions mocks base method.
func (m *MockLedgerServiceServer) BatchGetTransactions(arg0 context.Context, arg1 *rpcv2.BatchGetTransactionsRequest) (*rpcv2.BatchGetTransactionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetTransactions", arg0, arg1)
	ret0, _ := ret[0].(*rpcv2.BatchGetTransactionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetTransactions indicates an expected call of BatchGetTransactions.
func (mr *MockLedgerServiceServerMockRecorder) BatchGetTransactions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetTransactions", reflect.TypeOf((*MockLedgerServiceServer)(nil).BatchGetTransactions), arg0, arg1)
}

// GetCheckpoint mocks base method.
func (m *MockLedgerServiceServer) GetCheckpoint(arg0 context.Context, arg1 *rpcv2.GetCheckpointRequest) (*rpcv2.GetCheckpointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCheckpoint", arg0, arg1)
	ret0, _ := ret[0].(*rpcv2.GetCheckpointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCheckpoint indicates an expected call of GetCheckpoint.
func (mr *MockLedgerServiceServerMockRecorder) GetCheckpoint(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckpoint", reflect.TypeOf((*MockLedgerServiceServer)(nil).GetCheckpoint), arg0, arg1)
}

// GetEpoch mocks base method.
func (m *MockLedgerServiceServer) GetEpoch(arg0 context.Context, arg1 *rpcv2.GetEpochRequest) (*rpcv2.GetEpochResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpoch", arg0, arg1)
	ret0, _ := ret[0].(*rpcv2.GetEpochResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpoch indicates an expected call of GetEpoch.
func (mr *MockLedgerServiceServerMockRecorder) GetEpoch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpoch", reflect.TypeOf((*MockLedgerServiceServer)(nil).GetEpoch), arg0, arg1)
}

// GetObject mocks base method.
func (m *MockLedgerServiceServer) GetObject(arg0 context.Context, arg1 *rpcv2.GetObjectRequest) (*rpcv2.GetObjectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", arg0, arg1)
	ret0, _ := ret[0].(*rpcv2.GetObjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockLedgerServiceServerMockRecorder) GetObject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockLedgerServiceServer)(nil).GetObject), arg0, arg1)
}

// GetServiceInfo mocks base method.
func (m *MockLedgerServiceServer) GetServiceInfo(arg0 context.Context, arg1 *rpcv2.GetServiceInfoRequest) (*rpcv2.GetServiceInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceInfo", arg0, arg1)
	ret0, _ := ret[0].(*rpcv2.GetServiceInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceInfo indicates an expected call of GetServiceInfo.
func (mr *MockLedgerServiceServerMockRecorder) GetServiceInfo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceInfo", reflect.TypeOf((*MockLedgerServiceServer)(nil).GetServiceInfo), arg0, arg1)
}

// GetTransaction mocks base method.
func (m *MockLedgerServiceServer) GetTransaction(arg0 context.Context, arg1 *rpcv2.GetTransactionRequest) (*rpcv2.GetTransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", arg0, arg1)
	ret0, _ := ret[0].(*rpcv2.GetTransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockLedgerServiceServerMockRecorder) GetTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockLedgerServiceServer)(nil).GetTransaction), arg0, arg1)
}

// ListCheckpoints mocks base method.
func (m *MockLedgerServiceServer) ListCheckpoints(arg0 *rpcv2.ListCheckpointsRequest, arg1 grpc.ServerStreamingServer[rpcv2.ListCheckpointsResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCheckpoints", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListCheckpoints indicates an expected call of ListCheckpoints.
func (mr *MockLedgerServiceServerMockRecorder) ListCheckpoints(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCheckpoints", reflect.TypeOf((*MockLedgerServiceServer)(nil).ListCheckpoints), arg0, arg1)
}

// ListEvents mocks base method.
func (m *MockLedgerServiceServer) ListEvents(arg0 *rpcv2.ListEventsRequest, arg1 grpc.ServerStreamingServer[rpcv2.ListEventsResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockLedgerServiceServerMockRecorder) ListEvents(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockLedgerServiceServer)(nil).ListEvents), arg0, arg1)
}

// ListTransactions mocks base method.
func (m *MockLedgerServiceServer) ListTransactions(arg0 *rpcv2.ListTransactionsRequest, arg1 grpc.ServerStreamingServer[rpcv2.ListTransactionsResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockLedgerServiceServerMockRecorder) ListTransactions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockLedgerServiceServer)(nil).ListTransactions), arg0, arg1)
}

// mustEmbedUnimplementedLedgerServiceServer mocks base method.
func (m *MockLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedLedgerServiceServer")
}

// mustEmbedUnimplementedLedgerServiceServer indicates an expected call of mustEmbedUnimplementedLedgerServiceServer.
func (mr *MockLedgerServiceServerMockRecorder) mustEmbedUnimplementedLedgerServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedLedgerServiceServer", reflect.TypeOf((*MockLedgerServiceServer)(nil).mustEmbedUnimplementedLedgerServiceServer))
}

// MockUnsafeLedgerServiceServer is a mock of UnsafeLedgerServiceServer interface.
type MockUnsafeLedgerServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeLedgerServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeLedgerServiceServerMockRecorder is the mock recorder for MockUnsafeLedgerServiceServer.
type MockUnsafeLedgerServiceServerMockRecorder struct {
	mock *MockUnsafeLedgerServiceServer
}

// NewMockUnsafeLedgerServiceServer creates a new mock instance.
func NewMockUnsafeLedgerServiceServer(ctrl *gomock.Controller) *MockUnsafeLedgerServiceServer {
	mock := &MockUnsafeLedgerServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeLedgerServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeLedgerServiceServer) EXPECT() *MockUnsafeLedgerServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedLedgerServiceServer mocks base method.
func (m *MockUnsafeLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedLedgerServiceServer")
}

// mustEmbedUnimplementedLedgerServiceServer indicates an expected call of mustEmbedUnimplementedLedgerServiceServer.
func (mr *MockUnsafeLedgerServiceServerMockRecorder) mustEmbedUnimplementedLedgerServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedLedgerServiceServer", reflect.TypeOf((*MockUnsafeLedgerServiceServer)(nil).mustEmbedUnimplementedLedgerServiceServer))
}
