// Code generated by MockGen. DO NOT EDIT.
// Source: clientv2/internal/pb/sui/rpc/v2/state_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=clientv2/internal/pb/sui/rpc/v2/state_service_grpc.pb.go -destination=clientv2/internal/genmock/pb/sui/rpc/v2/state_service_grpc.pb.go
//

// Package mock_rpcv2 is a generated GoMock package.
package mock_rpcv2

import (
	context "context"
	reflect "reflect"

	rpcv2 "github.com/utila-io/go-sui-sdk/clientv2/internal/pb/sui/rpc/v2"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockStateServiceClient is a mock of StateServiceClient interface.
type MockStateServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockStateServiceClientMockRecorder
	isgomock struct{}
}

// MockStateServiceClientMockRecorder is the mock recorder for MockStateServiceClient.
type MockStateServiceClientMockRecorder struct {
	mock *MockStateServiceClient
}

// NewMockStateServiceClient creates a new mock instance.
func NewMockStateServiceClient(ctrl *gomock.Controller) *MockStateServiceClient {
	mock := &MockStateServiceClient{ctrl: ctrl}
	mock.recorder = &MockStateServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateServiceClient) EXPECT() *MockStateServiceClientMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockStateServiceClient) GetBalance(ctx context.Context, in *rpcv2.GetBalanceRequest, opts ...grpc.CallOption) (*rpcv2.GetBalanceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBalance", varargs...)
	ret0, _ := ret[0].(*rpcv2.GetBalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockStateServiceClientMockRecorder) GetBalance(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockStateServiceClient)(nil).GetBalance), varargs...)
}

// GetCoinInfo mocks base method.
func (m *MockStateServiceClient) GetCoinInfo(ctx context.Context, in *rpcv2.GetCoinInfoRequest, opts ...grpc.CallOption) (*rpcv2.GetCoinInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCoinInfo", varargs...)
	ret0, _ := ret[0].(*rpcv2.GetCoinInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoinInfo indicates an expected call of GetCoinInfo.
func (mr *MockStateServiceClientMockRecorder) GetCoinInfo(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoinInfo", reflect.TypeOf((*MockStateServiceClient)(nil).GetCoinInfo), varargs...)
}

// ListBalances mocks base method.
func (m *MockStateServiceClient) ListBalances(ctx context.Context, in *rpcv2.ListBalancesRequest, opts ...grpc.CallOption) (*rpcv2.ListBalancesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListBalances", varargs...)
	ret0, _ := ret[0].(*rpcv2.ListBalancesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBalances indicates an expected call of ListBalances.
func (mr *MockStateServiceClientMockRecorder) ListBalances(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBalances", reflect.TypeOf((*MockStateServiceClient)(nil).ListBalances), varargs...)
}

// ListDynamicFields mocks base method.
func (m *MockStateServiceClient) ListDynamicFields(ctx context.Context, in *rpcv2.ListDynamicFieldsRequest, opts ...grpc.CallOption) (*rpcv2.ListDynamicFieldsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDynamicFields", varargs...)
	ret0, _ := ret[0].(*rpcv2.ListDynamicFieldsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDynamicFields indicates an expected call of ListDynamicFields.
func (mr *MockStateServiceClientMockRecorder) ListDynamicFields(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDynamicFields", reflect.TypeOf((*MockStateServiceClient)(nil).ListDynamicFields), varargs...)
}

// ListOwnedObjects mocks base method.
func (m *MockStateServiceClient) ListOwnedObjects(ctx context.Context, in *rpcv2.ListOwnedObjectsRequest, opts ...grpc.CallOption) (*rpcv2.ListOwnedObjectsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListOwnedObjects", varargs...)
	ret0, _ := ret[0].(*rpcv2.ListOwnedObjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOwnedObjects indicates an expected call of ListOwnedObjects.
func (mr *MockStateServiceClientMockRecorder) ListOwnedObjects(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOwnedObjects", reflect.TypeOf((*MockStateServiceClient)(nil).ListOwnedObjects), varargs...)
}

// MockStateServiceServer is a mock of StateServiceServer interface.
type MockStateServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockStateServiceServerMockRecorder
	isgomock struct{}
}

// MockStateServiceServerMockRecorder is the mock recorder for MockStateServiceServer.
type MockStateServiceServerMockRecorder struct {
	mock *MockStateServiceServer
}

// NewMockStateServiceServer creates a new mock instance.
func NewMockStateServiceServer(ctrl *gomock.Controller) *MockStateServiceServer {
	mock := &MockStateServiceServer{ctrl: ctrl}
	mock.recorder = &MockStateServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateServiceServer) EXPECT() *MockStateServiceServerMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockStateServiceServer) GetBalance(arg0 context.Context, arg1 *rpcv2.GetBalanceRequest) (*rpcv2.GetBalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", arg0, arg1)
	ret0, _ := ret[0].(*rpcv2.GetBalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockStateServiceServerMockRecorder) GetBalance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockStateServiceServer)(nil).GetBalance), arg0, arg1)
}

// GetCoinInfo mocks base method.
func (m *MockStateServiceServer) GetCoinInfo(arg0 context.Context, arg1 *rpcv2.GetCoinInfoRequest) (*rpcv2.GetCoinInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoinInfo", arg0, arg1)
	ret0, _ := ret[0].(*rpcv2.GetCoinInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoinInfo indicates an expected call of GetCoinInfo.
func (mr *MockStateServiceServerMockRecorder) GetCoinInfo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoinInfo", reflect.TypeOf((*MockStateServiceServer)(nil).GetCoinInfo), arg0, arg1)
}

// ListBalances mocks base method.
func (m *MockStateServiceServer) ListBalances(arg0 context.Context, arg1 *rpcv2.ListBalancesRequest) (*rpcv2.ListBalancesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBalances", arg0, arg1)
	ret0, _ := ret[0].(*rpcv2.ListBalancesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBalances indicates an expected call of ListBalances.
func (mr *MockStateServiceServerMockRecorder) ListBalances(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBalances", reflect.TypeOf((*MockStateServiceServer)(nil).ListBalances), arg0, arg1)
}

// ListDynamicFields mocks base method.
func (m *MockStateServiceServer) ListDynamicFields(arg0 context.Context, arg1 *rpcv2.ListDynamicFieldsRequest) (*rpcv2.ListDynamicFieldsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDynamicFields", arg0, arg1)
	ret0, _ := ret[0].(*rpcv2.ListDynamicFieldsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDynamicFields indicates an expected call of ListDynamicFields.
func (mr *MockStateServiceServerMockRecorder) ListDynamicFields(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDynamicFields", reflect.TypeOf((*MockStateServiceServer)(nil).ListDynamicFields), arg0, arg1)
}

// ListOwnedObjects mocks base method.
func (m *MockStateServiceServer) ListOwnedObjects(arg0 context.Context, arg1 *rpcv2.ListOwnedObjectsRequest) (*rpcv2.ListOwnedObjectsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOwnedObjects", arg0, arg1)
	ret0, _ := ret[0].(*rpcv2.ListOwnedObjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOwnedObjects indicates an expected call of ListOwnedObjects.
func (mr *MockStateServiceServerMockRecorder) ListOwnedObjects(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOwnedObjects", reflect.TypeOf((*MockStateServiceServer)(nil).ListOwnedObjects), arg0, arg1)
}

// mustEmbedUnimplementedStateServiceServer mocks base method.
func (m *MockStateServiceServer) mustEmbedUnimplementedStateServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedStateServiceServer")
}

// mustEmbedUnimplementedStateServiceServer indicates an expected call of mustEmbedUnimplementedStateServiceServer.
func (mr *MockStateServiceServerMockRecorder) mustEmbedUnimplementedStateServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedStateServiceServer", reflect.TypeOf((*MockStateServiceServer)(nil).mustEmbedUnimplementedStateServiceServer))
}

// MockUnsafeStateServiceServer is a mock of UnsafeStateServiceServer interface.
type MockUnsafeStateServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeStateServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeStateServiceServerMockRecorder is the mock recorder for MockUnsafeStateServiceServer.
type MockUnsafeStateServiceServerMockRecorder struct {
	mock *MockUnsafeStateServiceServer
}

// NewMockUnsafeStateServiceServer creates a new mock instance.
func NewMockUnsafeStateServiceServer(ctrl *gomock.Controller) *MockUnsafeStateServiceServer {
	mock := &MockUnsafeStateServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeStateServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeStateServiceServer) EXPECT() *MockUnsafeStateServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedStateServiceServer mocks base method.
func (m *MockUnsafeStateServiceServer) mustEmbedUnimplementedStateServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedStateServiceServer")
}

// mustEmbedUnimplementedStateServiceServer indicates an expected call of mustEmbedUnimplementedStateServiceServer.
func (mr *MockUnsafeStateServiceServerMockRecorder) mustEmbedUnimplementedStateServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedStateServiceServer", reflect.TypeOf((*MockUnsafeStateServiceServer)(nil).mustEmbedUnimplementedStateServiceServer))
}
