// Code generated by MockGen. DO NOT EDIT.
// Source: clientv2/internal/pb/sui/rpc/v2/transaction_execution_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=clientv2/internal/pb/sui/rpc/v2/transaction_execution_service_grpc.pb.go -destination=clientv2/internal/genmock/pb/sui/rpc/v2/transaction_execution_service_grpc.pb.go
//

// Package mock_rpcv2 is a generated GoMock package.
package mock_rpcv2

import (
	context "context"
	reflect "reflect"

	rpcv2 "github.com/utila-io/go-sui-sdk/clientv2/internal/pb/sui/rpc/v2"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockTransactionExecutionServiceClient is a mock of TransactionExecutionServiceClient interface.
type MockTransactionExecutionServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionExecutionServiceClientMockRecorder
	isgomock struct{}
}

// MockTransactionExecutionServiceClientMockRecorder is the mock recorder for MockTransactionExecutionServiceClient.
type MockTransactionExecutionServiceClientMockRecorder struct {
	mock *MockTransactionExecutionServiceClient
}

// NewMockTransactionExecutionServiceClient creates a new mock instance.
func NewMockTransactionExecutionServiceClient(ctrl *gomock.Controller) *MockTransactionExecutionServiceClient {
	mock := &MockTransactionExecutionServiceClient{ctrl: ctrl}
	mock.recorder = &MockTransactionExecutionServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionExecutionServiceClient) EXPECT() *MockTransactionExecutionServiceClientMockRecorder {
	return m.recorder
}

// ExecuteTransaction mocks base method.
func (m *MockTransactionExecutionServiceClient) ExecuteTransaction(ctx context.Context, in *rpcv2.ExecuteTransactionRequest, opts ...grpc.CallOption) (*rpcv2.ExecuteTransactionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteTransaction", varargs...)
	ret0, _ := ret[0].(*rpcv2.ExecuteTransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteTransaction indicates an expected call of ExecuteTransaction.
func (mr *MockTransactionExecutionServiceClientMockRecorder) ExecuteTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTransaction", reflect.TypeOf((*MockTransactionExecutionServiceClient)(nil).ExecuteTransaction), varargs...)
}

// SimulateTransaction mocks base method.
func (m *MockTransactionExecutionServiceClient) SimulateTransaction(ctx context.Context, in *rpcv2.SimulateTransactionRequest, opts ...grpc.CallOption) (*rpcv2.SimulateTransactionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SimulateTransaction", varargs...)
	ret0, _ := ret[0].(*rpcv2.SimulateTransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SimulateTransaction indicates an expected call of SimulateTransaction.
func (mr *MockTransactionExecutionServiceClientMockRecorder) SimulateTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SimulateTransaction", reflect.TypeOf((*MockTransactionExecutionServiceClient)(nil).SimulateTransaction), varargs...)
}

// MockTransactionExecutionServiceServer is a mock of TransactionExecutionServiceServer interface.
type MockTransactionExecutionServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionExecutionServiceServerMockRecorder
	isgomock struct{}
}

// MockTransactionExecutionServiceServerMockRecorder is the mock recorder for MockTransactionExecutionServiceServer.
type MockTransactionExecutionServiceServerMockRecorder struct {
	mock *MockTransactionExecutionServiceServer
}

// NewMockTransactionExecutionServiceServer creates a new mock instance.
func NewMockTransactionExecutionServiceServer(ctrl *gomock.Controller) *MockTransactionExecutionServiceServer {
	mock := &MockTransactionExecutionServiceServer{ctrl: ctrl}
	mock.recorder = &MockTransactionExecutionServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionExecutionServiceServer) EXPECT() *MockTransactionExecutionServiceServerMockRecorder {
	return m.recorder
}

// ExecuteTransaction mocks base method.
func (m *MockTransactionExecutionServiceServer) ExecuteTransaction(arg0 context.Context, arg1 *rpcv2.ExecuteTransactionRequest) (*rpcv2.ExecuteTransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTransaction", arg0, arg1)
	ret0, _ := ret[0].(*rpcv2.ExecuteTransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteTransaction indicates an expected call of ExecuteTransaction.
func (mr *MockTransactionExecutionServiceServerMockRecorder) ExecuteTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTransaction", reflect.TypeOf((*MockTransactionExecutionServiceServer)(nil).ExecuteTransaction), arg0, arg1)
}

// SimulateTransaction mocks base method.
func (m *MockTransactionExecutionServiceServer) SimulateTransaction(arg0 context.Context, arg1 *rpcv2.SimulateTransactionRequest) (*rpcv2.SimulateTransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SimulateTransaction", arg0, arg1)
	ret0, _ := ret[0].(*rpcv2.SimulateTransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SimulateTransaction indicates an expected call of SimulateTransaction.
func (mr *MockTransactionExecutionServiceServerMockRecorder) SimulateTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SimulateTransaction", reflect.TypeOf((*MockTransactionExecutionServiceServer)(nil).SimulateTransaction), arg0, arg1)
}

// mustEmbedUnimplementedTransactionExecutionServiceServer mocks base method.
func (m *MockTransactionExecutionServiceServer) mustEmbedUnimplementedTransactionExecutionServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedTransactionExecutionServiceServer")
}

// mustEmbedUnimplementedTransactionExecutionServiceServer indicates an expected call of mustEmbedUnimplementedTransactionExecutionServiceServer.
func (mr *MockTransactionExecutionServiceServerMockRecorder) mustEmbedUnimplementedTransactionExecutionServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedTransactionExecutionServiceServer", reflect.TypeOf((*MockTransactionExecutionServiceServer)(nil).mustEmbedUnimplementedTransactionExecutionServiceServer))
}

// MockUnsafeTransactionExecutionServiceServer is a mock of UnsafeTransactionExecutionServiceServer interface.
type MockUnsafeTransactionExecutionServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeTransactionExecutionServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeTransactionExecutionServiceServerMockRecorder is the mock recorder for MockUnsafeTransactionExecutionServiceServer.
type MockUnsafeTransactionExecutionServiceServerMockRecorder struct {
	mock *MockUnsafeTransactionExecutionServiceServer
}

// NewMockUnsafeTransactionExecutionServiceServer creates a new mock instance.
func NewMockUnsafeTransactionExecutionServiceServer(ctrl *gomock.Controller) *MockUnsafeTransactionExecutionServiceServer {
	mock := &MockUnsafeTransactionExecutionServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeTransactionExecutionServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeTransactionExecutionServiceServer) EXPECT() *MockUnsafeTransactionExecutionServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedTransactionExecutionServiceServer mocks base method.
func (m *MockUnsafeTransactionExecutionServiceServer) mustEmbedUnimplementedTransactionExecutionServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedTransactionExecutionServiceServer")
}

// mustEmbedUnimplementedTransactionExecutionServiceServer indicates an expected call of mustEmbedUnimplementedTransactionExecutionServiceServer.
func (mr *MockUnsafeTransactionExecutionServiceServerMockRecorder) mustEmbedUnimplementedTransactionExecutionServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedTransactionExecutionServiceServer", reflect.TypeOf((*MockUnsafeTransactionExecutionServiceServer)(nil).mustEmbedUnimplementedTransactionExecutionServiceServer))
}
